---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbuckets.aws.platform.example.com
  labels:
    provider: aws
    service: storage
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XBucket
  
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      # S3 Bucket
      - name: bucket
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          spec:
            forProvider:
              region: us-east-1
            providerConfigRef:
              name: aws-default  # Default, será sobrescrito por patch
        
        patches:
        # Override manual tem prioridade (aplica primeiro)
        - type: FromCompositeFieldPath
          fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          policy:
            fromFieldPath: Optional  # Só aplica se estiver definido
        
        # Selecionar ProviderConfig baseado no ambiente (fallback se providerConfigName não for fornecido)
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.providerConfigRef.name
          transforms:
          - type: map
            map:
              dev: aws-dev
              hlm: aws-hml
              staging: aws-default
              prod: aws-prod
          policy:
            fromFieldPath: Required
        
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.tags[environment]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.costCenter
          toFieldPath: spec.forProvider.tags[cost-center]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.owner
          toFieldPath: spec.forProvider.tags[owner]
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
